# Generated by Django 3.1.3 on 2020-11-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('precio', models.IntegerField()),
                ('detalle', models.CharField(max_length=64)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.categoria')),
            ],
        ),
    ]
