# Generated by Django 3.1.3 on 2020-11-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='asistencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinica.asistencia'),
            preserve_default=False,
        ),
    ]
